### PR TITLE
Tom/DLS-9034 - remove deprecated service-integration-test

### PR DESCRIPTION
**Pull request by TomRafferty**

### CODE REVIEW

**Comment by johno1985** [comment]
can we address these PR bot comments?

**Comment by johno1985** [comment]
try addressing the sbt-plugin pr bot comment, it may affect compilation

**Comment by LAJW** [comment]
I couldn't figure out how to suppress logging in it:test.

**Comment by johno1985** [comment]
> I couldn't figure out how to suppress logging in it:test.

no worries, I can do that

**Review by johno1985 — APPROVED** [review]

**Pull request merged**
